POST http://localhost:8010/product

{
    "name": "hello",
    "price": 100500
}

###

GET http://localhost:8010/products

###

GET http://localhost:8010/product/1

###

PUT http://localhost:8010/product

{
    "id": 1,
    "name": "hello",
    "price": 100900
}


###

DELETE http://localhost:8010/products

###

POST http://localhost:8010/user

{
    "name": "hello",
    "city": "hagenberg",
    "zipcode": "4232"
}

###

GET http://localhost:8010/users